### PR TITLE
Replaced class methods with instance methods in bot logic

### PR DESCRIPTION
**Pull request by mraaroncruz**
Also updated rails to use the global `$bot` instead of class name

### CODE REVIEW

**Comment by mraaroncruz** [comment]
Crap, i think this breaks `@fb_params`

**Comment by mraaroncruz** [comment]
Nope, different error dealing with default args to quick_reply. False alarm. We good!

**Comment by davidmann4** [comment]
merge conflict because of code formating?

**Comment by mraaroncruz** [comment]
There you go. That was a good time 🎉

**Comment by davidmann4** [comment]
hmm I get an error with reply_message - any ideas?

**Comment by davidmann4** [comment]
NoMethodError (undefined method `sender' for #<Hash:0x007f63d93fc2c8>
Did you mean?  send):
  lib/bot/base_bot_logic.rb:20:in`reply_message'
  lib/bot/bot_logic.rb:20:in `bot_logic'
  lib/bot/base_bot_logic.rb:207:in`handle_request'
  app/bots/main.rb:7:in `block in <top (required)>'

  Rendered /home/cemputer/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/actionpack-4.2.6/lib/action_dispatch/middleware/templates/rescues/_source.erb (1.9ms)
  Rendered /home/cemputer/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/actionpack-4.2.6/lib/action_dispatch/middleware/templates/rescues/_trace.html.erb (1.6ms)
  Rendered /home/cemputer/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/actionpack-4.2.6/lib/action_dispatch/middleware/templates/rescues/_request_and_response.html.erb (0.8ms)
  Rendered /home/cemputer/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/actionpack-4.2.6/lib/action_dispatch/middleware/templates/rescues/diagnostics.html.erb within rescues/layout (14.4ms)

**Comment by davidmann4** [comment]
ahh guess I found the error nevermind

**Comment by davidmann4** [comment]
changes are great but I had problems with a bot I want to show tomorrow so I reverted it - will put it back soon!

**Pull request merged**
