### PR TITLE
Rename `reply_quick_reply` method to `reply_quick_buttons`

### PR DESCRIPTION
**Pull request by hola-soy-milk**
This also documents the use of `reply_quick_buttons` in the README.

### CODE REVIEW

**Comment by davidmann4** [comment]
great stuff!

**Comment by hola-soy-milk** [comment]
I'm glad you like it! Thanks for merging 🚀

**Comment by davidmann4** [comment]
hmmm maybe we could add some DSL for handling quick buttons:

``` ruby
on_quick_button "Yes"
  #logichere
end
```

**Comment by hola-soy-milk** [comment]
Interesting! I usually just use `get_message` for it

**Pull request merged**
